local f = io.open('KENAM.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 KENAM.sh')
os.execute('killall -9 tg')
os.execute('rm -rf KENAM.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('KENAM.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 KENAM.sh')
os.execute('screen ./KENAM.sh')
